baseURL = "https://beardahe.github.io/daheblog/"
languageCode = "zh-cn"
title = "BearDahe"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
homeInfoParams = { Title = "BearDahe", Content = " Welcome to Dahe's Blog " }

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowSocialIcons = true
ShowCodeCopyButtons = true
ShowToc = true
TocOpen = true

defaultTheme = "auto"
disableThemeToggle = false

ShowBreadCrumbs = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
ShowRssButton = true

ShowRecentPosts = true

assets = { disableHLJS = false }

[params.article]
  headerBackground = "var(--theme)"

[params.social]
X = "https://x.com/liuxiqinger"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "关于我"
    url = "/about/"
    weight = 5
